### ISSUE TITLE
Missing SPI Device

### ISSUE THREAD

**Issue by snortman** [Hilscher/netPI-netx-programming-examples#2]
Hi,

Using a NIOT-E-NPI3-51-EN-RE device.  Followed instructions from README.md.    

Was able to install driver and build the code.

However, when attempting to run the EtherCAT slave example, I received the following error message:

![image](https://user-images.githubusercontent.com/12835258/38828669-b9c5d384-4184-11e8-89c5-a00a28ee9209.png)

**Comment by lemariva** [comment]
No one is answering, so I try: 
Did you forget to map the device in the container setup? You need to map the spi interface like:

![hilscher](https://user-images.githubusercontent.com/15173329/41549906-9221fdc4-7327-11e8-8510-b42dca7c91d4.png)

You can type:
`ls /dev/spi*`
inside the container and you should get `/dev/spidev0.0` as answer. Otherwise, you didn't link the host device with the Docker container.

**Comment by hilschernetpi** [comment]
The communication between the netPI (Raspberry CPU) and netX chip goes across an SPI interface. On netPI this device is named spidev0.0 and as usual on Linux such devices are located in the /dev/ folder. If a container is now started under Docker, by default no host devices are mapped into a container, so you have to map it yourself. And as @lemariva has already mentioned you have to use the **Runtime** menu item and **+add device option** to insert a new line adding the **/dev/spidev0.0 -> /dev/spidev0.0** device entry.
